config/routes.rb
Rails.application.routes.draw do
  get 'favourites/update'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#home"
  
#  resources :posts, only: [:show, :index, :new, :create,:edit, :update]
resources :favourites, only: [:index]
resources :posts do
resources :comments, only: [:create, :destroy]
resources :likes
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :popular,-> { select('post_id,count(post_id)as count').group(:post_id).order('count desc').limit(10)}

  scope :popular1,-> { select('post_id,count(post_id)as count').group(:post_id).order('count asc').limit(10)}
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    has_many :comments,dependent: :destroy 
    has_many :likes
    belongs_to :user
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  has_many :likes
  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    def favourite_text
        return @favourite_exists ? "💔unfavourite" : " 💗Favourite"

    end
 
    def logged_in?
        !!current_user
      end

    helper_method  :favourite_text,:logged_in?
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :comment))
        redirect_to post_path(@post)
        end
        def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
        end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
 def index
 end
 
 
  def update

    favourite = Favourite.where(post: Post.find(params[:post]), user: current_user)
  
    if favourite == []
  
      # Create the favorite
  
      Favourite.create(post: Post.find(params[:post]), user: current_user)
  
      @favourite_exists = true
  
    else
  
      # Delete the favorite(s)
  
      favourite.destroy_all
  
      @favourite_exists = false
  
    end
  
  
  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_post
    before_action :find_like, only: [:destroy]
    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
          else
            @post.likes.create(user_id: current_user.id)
          end
          redirect_to post_path(@post)
    end

    def find_like
      @like = @post.likes.find(params[:id])
   end

    def destroy
      if !(already_liked?)
        flash[:notice] = "Cannot unlike"
      else
        @like.destroy
      end
      redirect_to post_path(@post)
    end

    private
    def find_post
      @post = Post.find(params[:post_id])
    end
    def already_liked?
        Like.where(user_id: current_user.id, post_id:
        params[:post_id]).exists?
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

def show
    # @post = Post.find(params[:id])
    @favourite_exists = Favourite.where(post: @post,user: current_user)==[]? false : true
end

def index
    @posts = Post.all
  end
 
def new
    @post = Post.new
end

def edit
    # @post = Post.find(params[:id])
  end



  def create
    # @post = Post.new(params.require(:post).permit(:title, :description))
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
        flash[:notice] = "Post was created successfully."
        redirect_to @post
      else
        render 'new'
      end
  end 

  def update
    # @post = Post.find(params[:id])
    # if @post.update(params.require(:post).permit(:title, :description))
     
      if @post.update(post_params)
      flash[:notice] = "Post was updated successfully."
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    
    @post = Post.find(params[:id])
    
    @post.destroy

    redirect_to  new_post_path
  
  end

  def favourite
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/_comment.html.erb
<div class="box">
<p><strong>by <%= comment.name %>:</strong>
<%= comment.comment %>
</p><br>
<%= link_to 'Delete', [comment.post, comment], data: { turbo_confirm: "are you sure?",turbo_method: :delete } %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], local: true) do |f| %>
<p>
<%= f.label :name %><br>
<%= f. text_field :name %>
</p>
<p>
<%= f.label :comment %><br>
<%= f. text_area :comment %>
</p>
<p>
<%= f.submit %>
<p>
<% end %>

app/views/favourites/index.html.erb
<div class:"container">

<h1> Your Favorite Posts</h1>



<% current_user.favourites.each do |favourite| %>

    <%= link_to favourite.post.title,favourite.post %>

    <br>

    <% end %>

</div>
<%= link_to 'Return to posts listing', posts_path %>

app/views/favourites/update.js.erb
$('#favourite_link').text("favourite_text")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instapost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

 <%= render template:"layouts/navigational" %>
   
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
 
    <%= yield %>
  </body>
</html>

app/views/layouts/navigational.html.erb
   <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">INSTAPOST</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class=" topnav-right navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu" >
           
            <li><a class="dropdown-item"  <%= link_to 'Favourited posts', favourites_path%>
</a></li>
            <li><a class="dropdown-item" 

<%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }%></a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Edit article</h1>

<% if @post.errors.any? %>



  <h2>The following errors prevented the post from being saved</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @post, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
<%= link_to 'Cancel and return to Posts listing', posts_path %>

app/views/posts/favourite.html.erb
<h1> Your Favorite Posts</h1>



<% current_user.favourites.each do |favourite| %>

    <%= link_to favourite.post.title,favourite.post %>

    <br>

    <% end %>

app/views/posts/form.html.erb
 <% if @post.errors.any? %>
  <h2>The following errors prevented the post from being saved</h2>
  <ul>
 
 
 
   <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @post, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/home.html.erb
<h>hi</h>

<%= link_to 'Posts listing', posts_path %>

<%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }%>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
<div class="text-center">


<h1>Posts listing page</h1>





   

    <%= link_to 'Favourited posts', favourites_path%>

<div class="m-5">
<h3> Most Engaged posts with likes and comments</h3>

<table class="center test">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>created by</th>
       <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody> 
<% popular = Like.popular %>

<% popular.each do |like|%>
<tr>
 <td><%= like.post.title%></td>
 <td><%= like.post.description%></td>
   <td><%= like.post.user.email  %></td>
    <td><%= link_to 'Show', post_path(like.post) %></td>

  <% if logged_in? && (like.post.user == current_user ) %>
       <td><%= link_to 'Edit', edit_post_path(like.post) %></td>
        <td><%= link_to 'Delete', post_path(like.post), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }  %></td>
 <%end%>
     </tr>
  
<% end %>
  </tbody>
</table>

</div>






<div class="mb-3 ">
<h3>  posts</h3>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>created by</th>
       <th colspan="3">Actions</th>
    </tr>
  </thead>

 <tbody>
<% array =[]%>
<% popular = Like.popular1%>

<% popular.each do |like|%>
  <% array.push(like.post)%>
<% end %>

 <% @posts.each do |post| %> 
  <%if array.include?(post)==true%>
     <% s= "do nothing"%>
     <%else%>
    <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.user.email if post.user %></td>
       <td><%= link_to 'Show', post_path(post) %></td>
       
  <% if logged_in? && (post.user == current_user ) %>
       <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post_path(post), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }  %></td>
      <%end%>
      </tr>
     <%end%>
     <%end%>
       </tbody>
</table>
</div>
<p>
  <%= link_to 'Create new post', new_post_path %>
</p>

<p>note: to delete the post u must unfavourite it  if the post is favourited </p>

</div>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<% if @post.errors.any? %>
  <h2>The following errors prevented the post from being saved</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with scope: :post, url: posts_path, local: true do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Return to posts listing', posts_path %>

app/views/posts/show.html.erb
<div class="text-center">

<h1>Showing Post details</h1>

<p><strong>Title: </strong><%= @post.title %></p>
<p><strong>Description: </strong><%= @post.description %></p>


  <% if logged_in? && (@post.user == current_user ) %>
<%= link_to 'Edit', edit_post_path(@post) %> 
<br>
<p>to delete the post u must unfavourite it  if the post is favourited </p>
   <%= link_to 'Delete', post_path(@post), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }  %>
   <%end%>

<%= link_to favourite_text,favourites_update_path(post: @post),id:'favourite_link',remote: true %>
     
<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
  <%= button_to '👎', post_like_path(@post, pre_like), method: :delete %>
<% else %>
  <%= button_to '👍', post_likes_path(@post), method: :post %>
<% end %>



<p><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%></p>


<p><strong><%= @post.comments.count %></strong> Comments</p>
<%= render @post.comments %>
<h3>Leave a reply</h3>
<%= render 'comments/form' %>


  






<%= link_to 'Return to posts listing', posts_path %>
</div>